FROM       dustymabe/fedora-pdflatex
MAINTAINER dusty@dustymabe.com

# Install a few others needed for my resume
RUN dnf install -y texlive-hyphenat texlive-fancyhdr texlive-multirow texlive-titlesec && dnf clean all
